package com.company.enums;

public enum AdminStatus {
    CLICKED_ADD_PRODUCT,
    ADD_CATEGORY,
    CLICKED_REMOVE_PRODUCT,
    CLICKED_ADD_CATEGORY,
    SELECT_CATEGORY_FOR_ADD_PRODUCT,
    ENTERED_PRODUCT_NAME,
    ENTERED_PRODUCT_PRICE,
    ENTERED_CATEGORY_NAME,
    SELECT_CATEGORY_FOR_REMOVE_PRODUCT,

    SEND_PRODUCT_IMAGE,

    COMMIT_OR_ROLLBACK_ADD_PRODUCT,
    CHANGE_NAME_BY_ID,
    CLICKED_REMOVE_CATEGORY,
    CHANGE_NAME,
    DELETE_PRODUCT,
    DELETE_CATEGORY;
}
